app/models/models.py
from datetime import datetime
from __init__ import db, login_manager
from flask_login import UserMixin
import pytz


UTC = pytz.utc
Srb = pytz.timezone('Europe/Belgrade')


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    phone = db.Column(db.String(120), unique=True)
    company = db.Column(db.String(120))
    email = db.Column(db.String(120), nullable=False, unique=True)
    subject = db.Column(db.String(120))
    description = db.Column(db.String(240))
    date = db.Column(db.String(120))
    time = db.Column(db.String(120))

    def __repr__(self):
        return f"Contact('{self.name}', '{self.phone}', '{self.company}', '{self.email}', '{self.subject}', '{self.description}', '{self.date}', '{self.time}')"

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), nullable=False, unique=True)
    email = db.Column(db.String(120), nullable=False, unique=True)
    password = db.Column(db.String(20), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}','{self.email}', '{self.password}')"

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.now(Srb))
    comment = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

# db.drop_all()

app/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint, request, abort
from app.form.form import ContactForm, LoginForm, UpdateAdminForm, PostForm
from __init__ import db
from app.models.models import User, Contact, Post
from flask_login import login_user, current_user, logout_user, login_required
from app.services.user_service import UserService


web = Blueprint('web', __name__, template_folder='templates')


header = 'The Customer Service Support is available from 09:00 - 17:00.'


# Home route
@web.route("/")
@web.route("/home")
def home():
    contact = UserService.get_all_users()
    posts = Post.query.all()
    return render_template('index.html', contact=contact, posts=posts, header=header, title='Home')


# Login
@web.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('web.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data, email=form.email.data, password=form.password.data).first()
        if user:
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('web.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form, title='Login')


# Contact
@web.route("/contact", methods=['GET', 'POST'])
def contact():
    if current_user.is_authenticated:
        return redirect(url_for('web.home'))
    form = ContactForm()
    if form.validate_on_submit():
        contact = Contact(name=form.name.data, phone=form.phone.data, company=form.company.data,
                    email=form.email.data, subject=form.subject.data, description=form.description.data,
                    date=form.date.data, time=form.time.data)
        db.session.add(contact)
        db.session.commit()
        flash('You have successfully Contacted Us!', 'success')
        return redirect(url_for('web.login'))
    else:
        return render_template('contact.html', form=form, title='Contact')


# Logout
@web.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('web.home'))


# Admin Page
@web.route("/admin", methods=['GET', 'POST'])
@login_required
def admin():
    form = UpdateAdminForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.password = form.password.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('web.admin'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.password.data = current_user.password

    return render_template('admin.html', form=form, title='Admin')


# New comments
@web.route("/comments/new", methods=['GET', 'POST'])
@login_required
def new_comment():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, comment=form.comment.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!')
        return redirect(url_for('web.home'))
    return render_template('create_comment.html', form=form, title='Add Comments', legend='Add Comments')


# Manipulate special comments
@web.route("/comment/<int:post_id>")
@login_required
def comment(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('comment.html', title='post.title', post=post)


# Update comment
@web.route("/comment/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.comment = form.comment.data
        db.session.commit()
        flash('Your comment has been updated!', 'success')
        return redirect(url_for('web.comment', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.comment.data = post.comment
    return render_template('create_comment.html', form=form, title='Update Comments', legend='Update Comments')


app/templates/admin.html
<!doctype html>
<html lang="en">

{% include 'includes/head.html' %}


<body>



        
        <section class="flexCenter center">
                <h2 class="username_style">Hello {{ current_user.username }} !</h2>
                <p>Your email: {{ current_user.email }}</p>
                <p>Would you like to go back?</p>
                <p>Click <a href="/">here</a></p>
            </section>
            <section id="ph-contact">
                <div class="red">
                <h2 class="account_info">Update your account info</h2>
            {% block content %}
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                            {{ form.username(placeholder='Username')}}
                            {% if form.username.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {{ form.email(placeholder='Email')}}
                            {% if form.email.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {{ form.password(placeholder='Password')}}
                            {% if form.password.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                <button class="btn btn--green" type="submit" id="sendForm" value="submit" name="submit">Update</button>
                </form>
            <p class="already"> Would you like to go Back? <a href="{{ url_for('web.home') }}">Back</a></p>

            {% endblock content %}
             </div>
            </section>



	{% include 'includes/scripts.html' %}

</body>
</html>

app/templates/comment.html

<!DOCTYPE html>
<html lang="en">

{% include 'includes/head.html' %}

<body class="post-body">


        <div class="registration_data red">
            <h2 class="users">Post</h2>
            {% block content %}
            <div class="col-1-of-2">
              <p><span class="primary-color">Date:</span> {{ post.date_posted.strftime('%d/%m/%Y') }} <span class="primary-color">/</span> <span>{{ post.date_posted.strftime('%H:%M') }}</span></p>
              <p class=""><span class="primary-color">User:</span> {{ post.author.username }}</p>
              <p class=""><span class="primary-color">Title:</span> {{ post.title }}</p>
              <p class=""><span class="primary-color">Comment:</span> {{ post.comment }}</p>
              <p class="already">Go <a href="{{ url_for('web.home') }}"> back?</a></p>
            </div>
            <div class="col-1-of-2">
            {% if post.author== current_user %}
                <a class="btn btn--green" href="{{ url_for('web.update_comment', post_id=post.id) }}" >Update</a>
            </div>
           {% endif %}
        {% endblock content %}
        </div>




    {% include 'includes/scripts.html' %}
</body>
</html>

app/templates/contact.html
<!DOCTYPE html>
<html lang="en">

{% include 'includes/head.html' %}


<body>

    {% include 'includes/contact_form.html' %}





    {% include 'includes/scripts.html' %}



</body>
</html>

app/templates/create_comment.html
<!DOCTYPE html>
<html lang="en">

{% include 'includes/head.html' %}

<body>


    {% include 'includes/comment_form.html' %}




    {% include 'includes/scripts.html' %}
</body>
</html>

app/templates/includes/comment_form.html
<div class="center red">
    <legend class="users">{{ legend }}</legend>
</div>
    <section id="ph-contact" class="ph-section">
        <div class="red">
            {% block content %}
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                            {{ form.title(placeholder='Title')}}
                            {% if form.title.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {{ form.comment(placeholder='Comment')}}
                            {% if form.comment.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.comment.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}

                <button class="btn btn--green" type="submit" id="sendForm" value="submit" name="submit">Submit</button>
                </form>
                    <p class="already"> Would you like to go Back? <a href="{{ url_for('web.contact') }}">Back</a></p>
            {% endblock content %}
        </div>
    </section>

app/templates/includes/contact_form.html

<!-- Contact -->



<div class="center red">
	<h4> Contact Us</h4>
</div>
	<section id="ph-contact" class="ph-section">
		<div class="red">
			<form method="POST" action="">
                {{ form.hidden_tag() }}
				{{ form.name(placeholder="Name") }}

				{% if form.name.errors %}
					<div class="invalid-feedback">
						{% for error in form.name.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}	
				{{ form.phone(placeholder="Phone") }}

				{% if form.phone.errors %}
					<div class="invalid-feedback">
						{% for error in form.phone.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}					
				{{ form.company(placeholder="Company") }}

				{% if form.company.errors %}
					<div class="invalid-feedback">
						{% for error in form.company.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}					
				{{ form.email(placeholder="Email") }}

				{% if form.email.errors %}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}					
				{{ form.subject(placeholder="Subject") }}

				{% if form.subject.errors %}
					<div class="invalid-feedback">
						{% for error in form.subject.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}					
				<textarea name="description" id="message" placeholder="Problem description" required></textarea>
				{% if form.description.errors %}
					<div class="invalid-feedback">
						{% for error in form.description.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}					
				<div class="block_item">

					<input class="date" type="text" id="date" name="date" placeholder="Date" data-format="m/d/Y" data-disabled-day="Sunday" data-max-year="2023" data-min-year="2021"  data-large-mode="true" data-init-set="false" data-theme="date">
					{% if form.date.errors %}
					<div class="invalid-feedback">
						{% for error in form.date.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}
					<input type="text" id="time" name="time" placeholder="Time">
					{% if form.time.errors %}
					<div class="invalid-feedback">
						{% for error in form.time.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}
				</div>
                <button class="btn btn--green" type="submit" id="sendForm" value="submit" name="submit">Contact Us</button>
			</form>
			<p class="already"> Would you like to Login? <a href="{{ url_for('web.login') }}">Log In</a></p>
		</div>
	</section>

app/templates/includes/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/date.css')}}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/datedropper.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


    <title>{{ title }}</title>
</head>

app/templates/includes/login_form.html
<div class="center red">
    <h4>{{ header }} <br> <br> Log In</h4>
    <p>Test user: <br> Username: Test, <br> Email: test@gmail.com <br> Password: 1234</p>
</div>
<section id="ph-contact" class="ph-section">
    <div class="red">
        {% block content %}
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                        {{ form.username(placeholder='Username')}}
                        {% if form.username.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {{ form.email(placeholder='Email')}}
                        {% if form.email.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {{ form.password(placeholder='Password')}}
                        {% if form.password.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
            <button class="btn btn--green" type="submit" id="sendForm" value="submit" name="submit">Login</button>
            </form>
                <p class="already"> Would you like to contact Us? <a href="{{ url_for('web.contact') }}">Contact Us</a></p>
        {% endblock content %}
    </div>
</section>

app/templates/includes/nav.html
<nav>
    <div class="menu-icon">
      <i class="fa fa-bars fa-2x"></i>
    </div>

    <div class="menu">
      <ul>
		{% if current_user.is_authenticated %}
            <li><a href="{{ url_for('web.logout') }}">Logout</a></li>
            <li><a href="{{ url_for('web.admin') }}">Admin</a></li>
            <li><a href="{{ url_for('web.new_comment') }}">Comment</a></li>

        {% else %}
        <li><a href="{{ url_for('web.login') }}">Log In</a></li>
        <li><a href="{{ url_for('web.contact') }}">Contact Us</a></p>
        {% endif %}
      </ul>
    </div>
  </nav>

app/templates/includes/scripts.html
<script src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/main.js')}}"></script>
<script src="{{ url_for('static', filename='js/datedropper.js')}}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

app/templates/index.html
<!doctype html>
<html lang="en">

{% include 'includes/head.html' %}


<body>

	<header class="header">
		{% include 'includes/nav.html' %}
		{% if current_user.is_authenticated %}
		<div class="registration_data red">
			<h2 class="users">Clients</h2>
			<div class="col-1-of-3">
				<h2>Client: {{ contact[0].name }}</h2>
				<p> <span class="primary-color">Time and date when client registered:</span> {{ contact[0].date }} in {{ contact[0].time }}</p>
				<p><span class="primary-color">Phone number:</span> {{ contact[0].phone }}</p>
				<p><span class="primary-color">Company:</span> {{ contact[0].company }}</p>
				<p><span class="primary-color">Subject: </span>{{ contact[0].subject }}</p>
				<p><span class="primary-color">Problem description:</span> {{ contact[0].description }}</p>
			</div>
			<div class="col-1-of-3">
				<h2>Client: {{ contact[1].name }}</h2>
				<p> <span class="primary-color">Time and date when client registered:</span> {{ contact[1].date }} in {{ contact[1].time }}</p>
				<p><span class="primary-color">Phone number:</span> {{ contact[1].phone }}</p>
				<p><span class="primary-color">Company:</span> {{ contact[1].company }}</p>
				<p><span class="primary-color">Subject: </span>{{ contact[1].subject }}</p>
				<p><span class="primary-color">Problem description:</span> {{ contact[1].description }}</p>
			</div>
			<div class="col-1-of-3">
				<h2>Client: {{ contact[2].name }}</h2>
				<p> <span class="primary-color">Time and date when client registered:</span> {{ contact[2].date }} in {{ contact[2].time }}</p>
				<p><span class="primary-color">Phone number:</span> {{ contact[2].phone }}</p>
				<p><span class="primary-color">Company:</span> {{ contact[2].company }}</p>
				<p><span class="primary-color">Subject: </span>{{ contact[2].subject }}</p>
				<p><span class="primary-color">Problem description:</span> {{ contact[2].description }}</p>
			</div>
		</div>



        <div class="registration_data red">
            <h2 class="users">Posts</h2>
            {% block content %}
            {% for post in posts %}
              <p><span class="primary-color">Date:</span> {{ post.date_posted.strftime('%d/%m/%Y') }} <span class="primary-color">/</span> <span>{{ post.date_posted.strftime('%H:%M') }}</span></p>
              <p class=""><span class="primary-color">User:</span> {{ post.author.username }}</p>
              <p class=""><span class="primary-color">Title:</span> {{ post.title }} </p>
              <p class="comment"><span class="primary-color">Comment:</span> {{ post.comment }}</p>
              <p class="change_comment">Click <a class="here" href="{{ url_for('web.comment', post_id=post.id) }}"> Here</a>  to edit comment</p>
            {% endfor %}
        {% endblock content %}
        </div>




			{% else %}
			<div class="centered">
                <h4 class="header-title">{{ header }}</h4>
			</div>
			{% endif %}

	</header>


	{% include 'includes/scripts.html' %}

</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

{% include 'includes/head.html' %}

<body>


    {% include 'includes/login_form.html' %}




    {% include 'includes/scripts.html' %}
</body>
</html>